### ISSUE TITLE
업데이트 서버에 연결할수 없다면서 작동이 안되네요

### ISSUE THREAD

**Issue by mocxlbor** [Potato-Y/Game-Utility-App#4]

**Comment by Potato-Y** [comment]
안녕하세요.
확인해 보니, Github에 업로드되어 있는 업데이트 정보를 받아올 수 없는 문제가 생긴 것 같습니다.
해당 문제는 제가 업데이트를 새로 배포하더라도 기존 버전을 사용하는 사용자는 업데이트를 받을 수 없습니다.

해당 문제가 해결된 버전이 배포되면 이슈를 통해 알려드리고, 기타 커뮤니티에도 다시 배포하도록 하겠습니다.
감사합니다.

**Comment by Potato-Y** [comment]
안녕하세요. 
문제가 수정된 버전이 배포되었습니다.
[UpdateClient.exe](https://github.com/Potato-Y/Game-Utility-App/releases/download/v1.5.10/UpdateClient.exe) 업데이트 클라이언트 파일을 다운로드 한 다음에, 기존 Game Utility App이 위치한 곳에 옮겨주세요. 
업데이트 클라이언트를 실행한 다음에 업데이트를 하면 정상적으로 이용하실 수 있습니다.

감사합니다.
